#!/usr/bin/env bash
# Script to generate the images list for https://hub.nspawn.org/images/
# and https://hub.nspawn.org/storage/list.txt

if [ "$1" == "static" ]; then
  find -maxdepth 3 -not -path '*/\.*' -not -empty -print |cut -c 3- |tr '/' ' ' |sort |awk 'NF == 3' |tr ' ' '/' | awk -F/ 'BEGIN {printf("%13s | %10s | %33s \n%13s | %10s | %33s\n" ,"DISTRO", "VERSION", "INIT COMMAND", "-------------", "----------", "---------------------------------")} {printf "%13s | %10s | nspawn -i %s/%s/%s\n", $1, $2, $1, $2, $3}' > /var/www/html/storage/list.txt
elif [ "$1" == "website" ]; then
  cd /var/www/nspawn.org/
  git pull
  sed -i -e '/Linux Distribution/,$d' /var/www/nspawn.org/content/images.md
  cd /var/www/html/storage/
  find  -maxdepth 3 -not -path '*/\.*' -not -empty -print |sort|cut -c 3- |tr '/' ' ' |awk 'NF == 3' |tr ' ' '/' | awk -F/ 'BEGIN {printf("|%s|%s|%s|%s|%s|\n|%s|%s|%s|%s|%s|\n" ,"Linux Distribution", "Distribution Version", "Image Type", "Nspawn Init Command", "Download Link", "-------------", "---------", "---------", "-------------", "------------")} {printf "|%s|%s|%s|nspawn -i %s/%s/%s|[%s-%s-%s](/storage/%s/%s/%s/image.%s.zstd)|\n", toupper(substr($1,1,1))substr($1,2), $2, $3, $1, $2, $3, $1, $2, $3, $1, $2, $3, $3}' >> /var/www/nspawn.org/content/images.md
  cd /var/www/nspawn.org/
  hugo -D
fi
