//! The files that make the bus start the service: the bus policy, the activation file
//! and the unit. Written with the path of this very binary.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result};

use crate::api::require_root;
use crate::daemon::BUS_NAME;

pub const POLICY: &str = "/etc/dbus-1/system.d/org.nspawn.conf";
pub const ACTIVATION: &str = "/usr/share/dbus-1/system-services/org.nspawn.service";
pub const UNIT: &str = "/etc/systemd/system/nspawn.service";

pub fn policy_text() -> String {
    format!(
        r#"<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<!-- Generated by nspawn (daemon install); do not edit. -->
<busconfig>
  <policy user="root">
    <allow own="{BUS_NAME}"/>
    <allow send_destination="{BUS_NAME}"/>
  </policy>
  <policy context="default">
    <allow send_destination="{BUS_NAME}" send_interface="org.freedesktop.DBus.Introspectable"/>
    <allow send_destination="{BUS_NAME}" send_interface="org.freedesktop.DBus.Properties" send_member="Get"/>
    <allow send_destination="{BUS_NAME}" send_interface="org.freedesktop.DBus.Properties" send_member="GetAll"/>
    <allow send_destination="{BUS_NAME}" send_interface="org.freedesktop.DBus.Peer"/>
    <allow receive_sender="{BUS_NAME}"/>
  </policy>
</busconfig>
"#
    )
}

pub fn activation_text() -> String {
    format!(
        "# Generated by nspawn (daemon install); do not edit.\n[D-BUS Service]\nName={BUS_NAME}\nExec=/bin/false\nUser=root\nSystemdService=nspawn.service\n"
    )
}

pub fn unit_text(binary: &Path, config: Option<&Path>) -> String {
    let mut exec = format!("{} daemon", binary.display());
    if let Some(config) = config {
        exec.push_str(&format!(" --config {}", config.display()));
    }
    format!(
        "# Generated by nspawn (daemon install); do not edit.\n[Unit]\nDescription=nspawn manager\nDocumentation=https://github.com/nspawn/nspawn\n\n[Service]\nType=dbus\nBusName={BUS_NAME}\nExecStart={exec}\n"
    )
}

/// The SELinux policy the service needs where SELinux is enforcing. The service runs
/// unconfined (unconfined_service_t) and hands pipes and pseudo terminals to its clients
/// over the bus; the base policy lets no domain touch the pipes of an unconfined
/// service (a dontaudit rule, so nothing is logged), and dbus-broker drops a peer whose
/// descriptors it cannot receive. machined has such rules of its own; this is ours.
pub const SELINUX_MODULE: &str = "nspawn";

pub fn selinux_module_text() -> String {
    format!(
        "module {SELINUX_MODULE} 1.0;

require {{
    type system_dbusd_t;
    type unconfined_service_t;
    type devpts_t;
    type ptmx_t;
    class fd use;
    class fifo_file {{ append getattr ioctl lock open read write }};
    class chr_file {{ append getattr ioctl lock open read write }};
}}

# The bus relays the pipes and pseudo terminals nspawn's service hands to its clients.
allow system_dbusd_t unconfined_service_t:fd use;
allow system_dbusd_t unconfined_service_t:fifo_file {{ append getattr ioctl lock open read write }};
allow system_dbusd_t devpts_t:chr_file {{ append getattr ioctl lock open read write }};
allow system_dbusd_t ptmx_t:chr_file {{ append getattr ioctl lock open read write }};
"
    )
}

fn selinux_enabled() -> bool {
    Path::new("/sys/fs/selinux/enforce").exists()
}

fn have(program: &str) -> bool {
    std::env::var_os("PATH")
        .is_some_and(|paths| std::env::split_paths(&paths).any(|dir| dir.join(program).is_file()))
}

fn run_tool(program: &str, args: &[&str], dir: &Path) -> Result<()> {
    let output = std::process::Command::new(program)
        .args(args)
        .current_dir(dir)
        .output()
        .with_context(|| format!("running {program}"))?;
    if !output.status.success() {
        anyhow::bail!(
            "{program} {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(())
}

/// Builds and loads the policy module. Returns what happened, one line.
fn install_selinux_module(state_dir: &Path) -> Result<String> {
    if !selinux_enabled() {
        return Ok("SELinux is not enabled here; no policy module needed".to_string());
    }
    let missing: Vec<&str> = ["checkmodule", "semodule_package", "semodule"]
        .into_iter()
        .filter(|tool| !have(tool))
        .collect();
    if !missing.is_empty() {
        return Ok(format!(
            "note: SELinux is enabled but {} not found (packages checkpolicy and policycoreutils); without the {SELINUX_MODULE} policy module the bus cannot relay the descriptors of Exec and Logs",
            missing.join(", ")
        ));
    }
    let dir = state_dir.join("selinux");
    fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
    fs::write(
        dir.join(format!("{SELINUX_MODULE}.te")),
        selinux_module_text(),
    )?;
    run_tool(
        "checkmodule",
        &[
            "-M",
            "-m",
            "-o",
            &format!("{SELINUX_MODULE}.mod"),
            &format!("{SELINUX_MODULE}.te"),
        ],
        &dir,
    )?;
    run_tool(
        "semodule_package",
        &[
            "-o",
            &format!("{SELINUX_MODULE}.pp"),
            "-m",
            &format!("{SELINUX_MODULE}.mod"),
        ],
        &dir,
    )?;
    run_tool("semodule", &["-i", &format!("{SELINUX_MODULE}.pp")], &dir)?;
    Ok(format!(
        "loaded the SELinux policy module {SELINUX_MODULE} (source in {})",
        dir.display()
    ))
}

/// Writes the three files, loads the SELinux policy where needed and tells systemd and
/// the bus about it all. Returns one line per thing done.
pub async fn install(config_path: Option<&Path>, state_dir: &Path) -> Result<Vec<String>> {
    require_root("daemon --install")?;
    let binary = std::env::current_exe().context("locating the nspawn binary")?;
    let binary = fs::canonicalize(&binary).unwrap_or(binary);
    let files = [
        (PathBuf::from(POLICY), policy_text()),
        (PathBuf::from(ACTIVATION), activation_text()),
        (PathBuf::from(UNIT), unit_text(&binary, config_path)),
    ];
    let mut done = Vec::new();
    for (path, text) in &files {
        if let Some(dir) = path.parent() {
            fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
        }
        fs::write(path, text).with_context(|| format!("writing {}", path.display()))?;
        done.push(format!("wrote {}", path.display()));
    }
    done.push(install_selinux_module(state_dir)?);
    let connection = zbus::Connection::system()
        .await
        .context("connecting to the system bus")?;
    zbus_systemd::systemd1::ManagerProxy::new(&connection)
        .await?
        .reload()
        .await
        .context("reloading systemd units")?;
    // dbus-daemon reads its policy and activation files on request; dbus-broker watches
    // them, and takes the request as well.
    zbus::fdo::DBusProxy::new(&connection)
        .await?
        .reload_config()
        .await
        .context("asking the bus to reload its configuration")?;
    Ok(done)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_files() {
        assert!(policy_text().contains("<allow own=\"org.nspawn\"/>"));
        assert!(activation_text().contains("SystemdService=nspawn.service"));
        let unit = unit_text(Path::new("/usr/local/bin/nspawn"), None);
        assert!(unit
            .contains("Type=dbus\nBusName=org.nspawn\nExecStart=/usr/local/bin/nspawn daemon\n"));
        let with_config = unit_text(Path::new("/usr/bin/nspawn"), Some(Path::new("/etc/x.toml")));
        assert!(with_config.contains("ExecStart=/usr/bin/nspawn daemon --config /etc/x.toml\n"));
        let module = selinux_module_text();
        assert!(module.starts_with("module nspawn 1.0;"));
        assert!(module.contains("allow system_dbusd_t unconfined_service_t:fifo_file"));
        assert!(module.contains("allow system_dbusd_t devpts_t:chr_file"));
    }
}
