//! The files that make the bus start the service: the bus policy, the activation file
//! and the unit. Written with the path of this very binary.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result};

use crate::api::require_root;
use crate::daemon::BUS_NAME;

pub const POLICY: &str = "/etc/dbus-1/system.d/org.nspawn.conf";
pub const ACTIONS: &str = "/usr/share/polkit-1/actions/org.nspawn.policy";
pub const ACTIVATION: &str = "/usr/share/dbus-1/system-services/org.nspawn.service";
pub const UNIT: &str = "/etc/systemd/system/nspawn.service";

pub fn policy_text() -> String {
    format!(
        r#"<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<!-- Generated by nspawn (daemon install); do not edit. -->
<busconfig>
  <policy user="root">
    <allow own="{BUS_NAME}"/>
    <allow send_destination="{BUS_NAME}"/>
  </policy>
  <policy context="default">
    <allow send_destination="{BUS_NAME}"/>
    <allow receive_sender="{BUS_NAME}"/>
  </policy>
</busconfig>
"#
    )
}

/// The actions polkit knows nspawn by. Both are for administrators by default; a rule
/// of the administrator's own can hand either to a group (packaging/polkit has one).
pub fn actions_text() -> String {
    let packaged = include_str!("../../packaging/polkit/org.nspawn.policy");
    packaged.replace(
        "<policyconfig>",
        "<policyconfig>\n  <!-- Generated by nspawn (daemon install); do not edit. -->",
    )
}

pub fn activation_text() -> String {
    format!(
        "# Generated by nspawn (daemon install); do not edit.\n[D-BUS Service]\nName={BUS_NAME}\nExec=/bin/false\nUser=root\nSystemdService=nspawn.service\n"
    )
}

pub fn unit_text(binary: &Path, config: Option<&Path>) -> String {
    let mut exec = format!("{} daemon", binary.display());
    if let Some(config) = config {
        exec.push_str(&format!(" --config {}", config.display()));
    }
    format!(
        "# Generated by nspawn (daemon install); do not edit.\n[Unit]\nDescription=nspawn manager\nDocumentation=https://github.com/nspawn/nspawn\n\n[Service]\nType=dbus\nBusName={BUS_NAME}\nExecStart={exec}\n"
    )
}

/// Writes the three files and tells systemd and the bus about them. Returns one line per
/// file. On a host with SELinux enforcing the service also needs the policy module the
/// packages ship (packaging/selinux): the bus drops a service without a domain the
/// moment it hands a descriptor over.
pub async fn install(config_path: Option<&Path>) -> Result<Vec<String>> {
    require_root("daemon --install")?;
    let binary = std::env::current_exe().context("locating the nspawn binary")?;
    let binary = fs::canonicalize(&binary).unwrap_or(binary);
    let files = [
        (PathBuf::from(POLICY), policy_text()),
        (PathBuf::from(ACTIONS), actions_text()),
        (PathBuf::from(ACTIVATION), activation_text()),
        (PathBuf::from(UNIT), unit_text(&binary, config_path)),
    ];
    let mut done = Vec::new();
    for (path, text) in &files {
        if let Some(dir) = path.parent() {
            fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
        }
        fs::write(path, text).with_context(|| format!("writing {}", path.display()))?;
        done.push(format!("wrote {}", path.display()));
    }
    if Path::new("/sys/fs/selinux/enforce").exists()
        && !std::process::Command::new("semodule")
            .args(["-l"])
            .output()
            .map(|o| {
                String::from_utf8_lossy(&o.stdout)
                    .lines()
                    .any(|l| l == "nspawn")
            })
            .unwrap_or(false)
    {
        done.push("note: SELinux is enabled and the nspawn policy module is not loaded; install the nspawn-selinux package, or Exec, Shell and Logs will not work on the bus (see docs/DBUS.md)".to_string());
    }
    let connection = zbus::Connection::system()
        .await
        .context("connecting to the system bus")?;
    zbus_systemd::systemd1::ManagerProxy::new(&connection)
        .await?
        .reload()
        .await
        .context("reloading systemd units")?;
    // dbus-daemon reads its policy and activation files on request; dbus-broker watches
    // them, and takes the request as well.
    zbus::fdo::DBusProxy::new(&connection)
        .await?
        .reload_config()
        .await
        .context("asking the bus to reload its configuration")?;
    Ok(done)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// What `--install` writes is what the packages ship, minus the generated header.
    #[test]
    fn generated_files_match_the_packaged_ones() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("packaging");
        let body = |text: String| {
            text.lines()
                .filter(|l| !l.contains("Generated by nspawn"))
                .collect::<Vec<_>>()
                .join("\n")
                + "\n"
        };
        let packaged = |path: &str| std::fs::read_to_string(root.join(path)).unwrap();
        assert_eq!(body(policy_text()), packaged("dbus/org.nspawn.conf"));
        assert_eq!(body(actions_text()), packaged("polkit/org.nspawn.policy"));
        assert_eq!(body(activation_text()), packaged("dbus/org.nspawn.service"));
        assert_eq!(
            body(unit_text(Path::new("/usr/bin/nspawn"), None)),
            packaged("systemd/nspawn.service")
        );
    }

    #[test]
    fn generated_files() {
        assert!(policy_text().contains("<allow own=\"org.nspawn\"/>"));
        // Everyone may call; polkit is what decides.
        assert!(policy_text().contains(
            "<policy context=\"default\">\n    <allow send_destination=\"org.nspawn\"/>"
        ));
        for action in ["org.nspawn.inspect", "org.nspawn.manage"] {
            assert!(
                actions_text().contains(&format!("<action id=\"{action}\">")),
                "{action}"
            );
        }
        assert!(activation_text().contains("SystemdService=nspawn.service"));
        let unit = unit_text(Path::new("/usr/local/bin/nspawn"), None);
        assert!(unit
            .contains("Type=dbus\nBusName=org.nspawn\nExecStart=/usr/local/bin/nspawn daemon\n"));
        let with_config = unit_text(Path::new("/usr/bin/nspawn"), Some(Path::new("/etc/x.toml")));
        assert!(with_config.contains("ExecStart=/usr/bin/nspawn daemon --config /etc/x.toml\n"));
    }
}
