//! The trusted systemd.nspawn(5) settings file nspawn keeps for every machine it manages.
//! The systemd-nspawn@.service template runs with --settings=override, so these values win
//! over its command line.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::oci::{Mode, RunSpec};

pub const SETTINGS_DIR: &str = "/etc/systemd/nspawn";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, clap::ValueEnum)]
#[serde(rename_all = "lowercase")]
pub enum Network {
    /// The nspawn bridge (docker0 style): fixed address, NAT, published ports, names of
    /// the other machines. Needs nothing from the host's own network manager.
    Bridge,
    /// A virtual ethernet pair configured by systemd-networkd on the host.
    Veth,
    /// Share the host's network namespace, like docker run --network host.
    Host,
}

pub struct MachineSettings<'a> {
    pub name: &'a str,
    /// mstack images: boot with managed user namespaces instead of the template's -U.
    pub managed_userns: bool,
    pub mode: Mode,
    /// Working directory, user, environment and stop signal of the image.
    pub run: &'a RunSpec,
    /// What an app machine runs: entrypoint and cmd, overrides applied.
    pub command: &'a [String],
    /// Environment given with -e, after the image's.
    pub extra_env: &'a [String],
    /// Volumes, resolved to host paths.
    pub binds: &'a [Bind],
    /// Directory with the units that make a managed-userns machine wait for its volumes
    /// (see `volume_wait_units`), when it has any.
    pub volume_units: Option<&'a Path>,
    pub network: Network,
    /// Bridge networking: the bridge to join and the directory with the machine's
    /// generated host0.network and hosts files.
    pub bridge: Option<BridgeMount<'a>>,
}

pub struct BridgeMount<'a> {
    pub bridge: &'a str,
    pub files: &'a Path,
}

/// A volume ready to mount.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Bind {
    pub source: PathBuf,
    pub target: String,
    pub read_only: bool,
}

pub fn path(name: &str) -> PathBuf {
    Path::new(SETTINGS_DIR).join(format!("{name}.nspawn"))
}

pub fn render(s: &MachineSettings) -> String {
    let mut out = format!(
        "# Generated by nspawn for image {}; do not edit.\n[Exec]\n",
        s.name
    );
    let mut private_users = true;
    if s.managed_userns {
        out.push_str("PrivateUsers=managed\n");
    } else if s.mode == Mode::App && s.network == Network::Bridge && s.bridge.is_some() {
        // A user namespace cannot join the network namespace prepared on the host
        // (EPERM: it belongs to the initial user namespace), so app machines on the
        // bridge run without one, as docker does.
        out.push_str("PrivateUsers=no\n");
        private_users = false;
    }
    match s.mode {
        Mode::Boot => out.push_str("Boot=yes\n"),
        Mode::App => {
            out.push_str("Boot=no\nProcessTwo=yes\n");
            if !s.command.is_empty() {
                let quoted: Vec<String> = s.command.iter().map(|a| quote(a)).collect();
                out.push_str(&format!("Parameters={}\n", quoted.join(" ")));
            }
            // A later assignment of the same variable wins, so -e comes after the image's.
            for var in s.run.env.iter().chain(s.extra_env) {
                out.push_str(&format!("Environment={}\n", quote(var)));
            }
            if let Some(dir) = &s.run.working_dir {
                out.push_str(&format!("WorkingDirectory={dir}\n"));
            }
            match &s.run.user {
                Some(user) if !user.chars().all(|c| c.is_ascii_digit() || c == ':') => {
                    out.push_str(&format!("User={user}\n"));
                }
                _ => {}
            }
            // What nspawn forwards to the stub init when the unit is stopped: a poweroff
            // request, which the stub answers with SIGTERM to the program and waits. The
            // image's own stop signal is what `nspawn stop` sends to the program itself.
            out.push_str("KillSignal=SIGRTMIN+4\n");
        }
    }
    let mut files: Vec<String> = Vec::new();
    match s.network {
        Network::Host => out.push_str("\n[Network]\nVirtualEthernet=no\n"),
        Network::Bridge => {
            if let Some(b) = &s.bridge {
                let dir = b.files.display();
                match s.mode {
                    // systemd-networkd inside configures host0 from the mounted file.
                    Mode::Boot => {
                        out.push_str(&format!("\n[Network]\nBridge={}\n", b.bridge));
                        files.push(format!(
                            "BindReadOnly={dir}/host0.network:/run/systemd/network/10-host0.network"
                        ));
                        files.push(format!("BindReadOnly={dir}/hosts:/etc/hosts"));
                    }
                    // Nothing inside to configure anything: the namespace comes ready.
                    Mode::App => {
                        out.push_str(&format!(
                            "\n[Network]\nNamespacePath={}\n",
                            crate::bridge::netns_path(s.name)
                        ));
                        files.push(format!("BindReadOnly={dir}/hosts:/etc/hosts"));
                        files.push(format!("BindReadOnly={dir}/resolv.conf:/etc/resolv.conf"));
                    }
                }
            }
        }
        Network::Veth => {}
    }
    // Under managed user namespaces nspawn cannot idmap binds; those volumes are attached
    // from the host once the machine runs (see volmount), and a unit inside holds
    // local-fs.target until they are there, so that services find them.
    let rendered_binds: &[Bind] = if s.managed_userns { &[] } else { s.binds };
    if s.managed_userns && !s.binds.is_empty() {
        if let Some(units) = s.volume_units {
            let units = units.display();
            files.push(format!(
                "BindReadOnly={units}/nspawn-volumes.service:/run/systemd/system/nspawn-volumes.service"
            ));
            files.push(format!(
                "BindReadOnly={units}/nspawn-volumes.conf:/run/systemd/system/local-fs.target.d/nspawn-volumes.conf"
            ));
        }
    }
    for bind in rendered_binds {
        // With private users the host's uid 0 is nobody inside; idmap makes root inside
        // the owner of what it writes, as docker users expect.
        let options = if private_users { ":idmap" } else { "" };
        files.push(format!(
            "{}={}:{}{options}",
            if bind.read_only {
                "BindReadOnly"
            } else {
                "Bind"
            },
            bind.source.display(),
            bind.target
        ));
    }
    if !files.is_empty() {
        out.push_str("\n[Files]\n");
        for line in files {
            out.push_str(&line);
            out.push('\n');
        }
    }
    out
}

/// The units mounted into a managed-userns machine so that its boot waits for the volumes
/// nspawn attaches from the host: (service, drop-in for local-fs.target).
pub fn volume_wait_units(targets: &[String]) -> (String, String) {
    let list = targets
        .iter()
        .map(|t| quote(t))
        .collect::<Vec<_>>()
        .join(" ");
    let service = format!(
        "# Generated by nspawn; do not edit.\n[Unit]\nDescription=Wait for the volumes nspawn attaches from the host\nDefaultDependencies=no\nBefore=local-fs.target\n\n[Service]\nType=oneshot\nRemainAfterExit=yes\nExecStart=/bin/sh -c 'for p in {list}; do i=0; until mountpoint -q \"$p\"; do i=$((i+1)); if [ $i -ge 200 ]; then echo \"$p: volume not attached\" >&2; exit 1; fi; sleep 0.05; done; done'\n"
    );
    let dropin = "# Generated by nspawn; do not edit.\n[Unit]\nWants=nspawn-volumes.service\nAfter=nspawn-volumes.service\n".to_string();
    (service, dropin)
}

/// Writes the file when it differs from what is there.
pub fn write(s: &MachineSettings) -> Result<()> {
    let path = path(s.name);
    let wanted = render(s);
    if fs::read_to_string(&path)
        .map(|current| current == wanted)
        .unwrap_or(false)
    {
        return Ok(());
    }
    fs::create_dir_all(SETTINGS_DIR).with_context(|| format!("creating {SETTINGS_DIR}"))?;
    fs::write(&path, wanted).with_context(|| format!("writing {}", path.display()))
}

pub fn remove(name: &str) {
    let _ = fs::remove_file(path(name));
}

/// Quotes one argument the way systemd's config parser (config_parse_strv) reads it:
/// quotes group, backslashes are kept literally and never escape anything, and adjacent
/// quoted pieces join into one word. So the whole argument goes in single quotes, and
/// each single quote it contains rides in double quotes between two such pieces.
pub fn quote(arg: &str) -> String {
    if !arg.is_empty()
        && !arg
            .chars()
            .any(|c| c.is_whitespace() || matches!(c, '"' | '\'' | '\\'))
    {
        return arg.to_string();
    }
    let mut out = String::new();
    for (i, piece) in arg.split('\'').enumerate() {
        if i > 0 {
            out.push_str("\"'\"");
        }
        if !piece.is_empty() {
            out.push('\'');
            out.push_str(piece);
            out.push('\'');
        }
    }
    if out.is_empty() {
        "''".to_string()
    } else {
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quoting() {
        assert_eq!(quote("nginx"), "nginx");
        assert_eq!(quote("daemon off;"), "'daemon off;'");
        assert_eq!(quote("a\"b"), "'a\"b'");
        assert_eq!(quote("it's"), "'it'\"'\"'s'");
        assert_eq!(quote("'"), "\"'\"");
        assert_eq!(quote("back\\slash"), "'back\\slash'");
        assert_eq!(quote(""), "''");
        assert_eq!(quote("PATH=/usr/bin"), "PATH=/usr/bin");
        assert_eq!(quote("/bin/sh"), "/bin/sh");
    }

    #[test]
    fn renders_boot_and_app_machines() {
        let run = RunSpec::default();
        let boot = render(&MachineSettings {
            name: "fedora-44",
            managed_userns: true,
            mode: Mode::Boot,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Veth,
            bridge: None,
        });
        assert_eq!(boot, "# Generated by nspawn for image fedora-44; do not edit.\n[Exec]\nPrivateUsers=managed\nBoot=yes\n");

        let bridged = render(&MachineSettings {
            name: "fedora-44",
            managed_userns: false,
            mode: Mode::Boot,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Bridge,
            bridge: Some(BridgeMount {
                bridge: "nspawn0",
                files: Path::new("/var/lib/nspawn/machines/fedora-44"),
            }),
        });
        assert!(bridged.contains("Boot=yes\n\n[Network]\nBridge=nspawn0\n\n[Files]\n"));
        assert!(bridged.contains("BindReadOnly=/var/lib/nspawn/machines/fedora-44/host0.network:/run/systemd/network/10-host0.network\n"));
        assert!(
            bridged.ends_with("BindReadOnly=/var/lib/nspawn/machines/fedora-44/hosts:/etc/hosts\n")
        );

        let app_bridged = render(&MachineSettings {
            name: "web",
            managed_userns: false,
            mode: Mode::App,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Bridge,
            bridge: Some(BridgeMount {
                bridge: "nspawn0",
                files: Path::new("/var/lib/nspawn/machines/web"),
            }),
        });
        assert!(app_bridged.contains("[Exec]\nPrivateUsers=no\nBoot=no\n"));
        assert!(app_bridged.contains("[Network]\nNamespacePath=/run/netns/nspawn-web\n"));
        assert!(!app_bridged.contains("Bridge="));
        assert!(app_bridged.ends_with("BindReadOnly=/var/lib/nspawn/machines/web/hosts:/etc/hosts\nBindReadOnly=/var/lib/nspawn/machines/web/resolv.conf:/etc/resolv.conf\n"));
        let app_volume = render(&MachineSettings {
            name: "web",
            managed_userns: false,
            mode: Mode::App,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[Bind {
                source: PathBuf::from("/srv/www"),
                target: "/www".into(),
                read_only: false,
            }],
            volume_units: None,
            network: Network::Bridge,
            bridge: Some(BridgeMount {
                bridge: "nspawn0",
                files: Path::new("/var/lib/nspawn/machines/web"),
            }),
        });
        let mstack_volume = render(&MachineSettings {
            name: "db",
            managed_userns: true,
            mode: Mode::Boot,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[Bind {
                source: PathBuf::from("/srv/pg"),
                target: "/var/lib/pgsql".into(),
                read_only: false,
            }],
            volume_units: Some(Path::new("/var/lib/nspawn/machines/db/units")),
            network: Network::Host,
            bridge: None,
        });
        // Managed user namespaces: no Bind= (attached from the host), but the wait units.
        assert!(!mstack_volume.contains("Bind=/srv/pg"));
        assert!(mstack_volume.contains("BindReadOnly=/var/lib/nspawn/machines/db/units/nspawn-volumes.service:/run/systemd/system/nspawn-volumes.service\n"));
        assert!(mstack_volume.contains("local-fs.target.d/nspawn-volumes.conf\n"));
        let (service, dropin) =
            volume_wait_units(&["/var/lib/pgsql".to_string(), "/etc/app".to_string()]);
        assert!(service.contains("Before=local-fs.target"));
        assert!(service.contains("for p in /var/lib/pgsql /etc/app;"));
        assert!(dropin.contains("Wants=nspawn-volumes.service\nAfter=nspawn-volumes.service"));
        // No user namespace on the bridge, so no idmap either.
        assert!(app_volume.ends_with("BindReadOnly=/var/lib/nspawn/machines/web/resolv.conf:/etc/resolv.conf\nBind=/srv/www:/www\n"));

        let run = RunSpec {
            entrypoint: Vec::new(),
            cmd: vec!["nginx".into(), "-g".into(), "daemon off;".into()],
            command: Vec::new(),
            env: vec!["PATH=/usr/bin".into(), "GREETING=hello world".into()],
            working_dir: Some("/srv".into()),
            user: Some("nginx".into()),
            stop_signal: Some("SIGQUIT".into()),
        };
        let app = render(&MachineSettings {
            name: "web",
            managed_userns: false,
            mode: Mode::App,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Host,
            bridge: None,
        });
        assert!(app.contains("Boot=no\nProcessTwo=yes\n"));
        assert!(app.contains("Parameters=nginx -g 'daemon off;'\n"));
        assert!(app.contains("Environment=PATH=/usr/bin\nEnvironment='GREETING=hello world'\n"));
        assert!(app.contains("WorkingDirectory=/srv\nUser=nginx\nKillSignal=SIGRTMIN+4\n"));
        assert!(app.ends_with("[Network]\nVirtualEthernet=no\n"));

        let numeric_user = RunSpec {
            user: Some("1000:1000".into()),
            ..RunSpec::default()
        };
        let binds = vec![
            Bind {
                source: PathBuf::from("/srv/data"),
                target: "/data".into(),
                read_only: false,
            },
            Bind {
                source: PathBuf::from("/var/lib/nspawn/volumes/cfg"),
                target: "/etc/app".into(),
                read_only: true,
            },
        ];
        let text = render(&MachineSettings {
            name: "x",
            managed_userns: false,
            mode: Mode::App,
            run: &numeric_user,
            command: &["/bin/sleep".to_string(), "infinity".to_string()],
            extra_env: &["GREETING=hi".to_string()],
            binds: &binds,
            volume_units: None,
            network: Network::Veth,
            bridge: None,
        });
        assert!(!text.contains("User="));
        assert!(text.contains(
            "Parameters=/bin/sleep infinity\nEnvironment=GREETING=hi\nKillSignal=SIGRTMIN+4\n"
        ));
        assert!(!text.contains("[Network]"));
        // The template's -U applies here, so volumes are idmapped.
        assert!(text.ends_with("[Files]\nBind=/srv/data:/data:idmap\nBindReadOnly=/var/lib/nspawn/volumes/cfg:/etc/app:idmap\n"));
    }
}
