//! The trusted systemd.nspawn(5) file of each machine, and the unit's hooks drop-in. The
//! template runs with --settings=override, so the file wins over its command line.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::oci::{Mode, RunSpec};
use crate::policy::{Limits, Restart};
use crate::systemd::Systemd;

pub const SETTINGS_DIR: &str = "/etc/systemd/nspawn";

/// The settings key NamespacePath= exists since this systemd version.
pub const NAMESPACE_PATH_SETTING_SINCE: u32 = 259;

/// How an app on the bridge gets the network namespace prepared on the host.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NamespaceRoute {
    Settings,
    /// --network-namespace-path= on the command line: systemd before 259 has no key.
    CommandLine(Vec<String>),
}

/// `bridged`: the machine joins bridge networks (not veth, host or none).
pub async fn namespace_route(
    sd: &Systemd,
    name: &str,
    mode: Mode,
    bridged: bool,
) -> Result<NamespaceRoute> {
    if mode != Mode::App || !bridged {
        return Ok(NamespaceRoute::Settings);
    }
    if sd
        .major()
        .await
        .is_some_and(|major| major >= NAMESPACE_PATH_SETTING_SINCE)
    {
        return Ok(NamespaceRoute::Settings);
    }
    let unit = format!("systemd-nspawn@{name}.service");
    Ok(NamespaceRoute::CommandLine(sd.exec_start(&unit).await?))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, clap::ValueEnum)]
#[serde(rename_all = "lowercase")]
pub enum Network {
    /// The nspawn bridge: fixed address, NAT, published ports, the other machines' names.
    Bridge,
    /// A virtual ethernet pair configured by systemd-networkd on the host.
    Veth,
    /// The host's network namespace.
    Host,
}

pub struct MachineSettings<'a> {
    pub name: &'a str,
    /// mstack images: boot with managed user namespaces instead of the template's -U.
    pub managed_userns: bool,
    pub mode: Mode,
    pub run: &'a RunSpec,
    /// Entrypoint and cmd, overrides applied.
    pub command: &'a [String],
    /// -e, after the image's environment.
    pub extra_env: &'a [String],
    pub binds: &'a [Bind],
    /// The units that make a booted machine wait for its volumes (`volume_wait_units`).
    pub volume_units: Option<&'a Path>,
    pub network: Network,
    /// --network none: no interface but lo.
    pub no_network: bool,
    /// The bridges to join and the directory of the generated .network files and hosts.
    pub bridge: Option<BridgeMount<'a>>,
}

pub struct BridgeMount<'a> {
    /// The primary network's bridge.
    pub bridge: &'a str,
    pub files: &'a Path,
    /// The host ends of the veths on the other networks, host1.. inside.
    pub extras: &'a [String],
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Bind {
    pub source: PathBuf,
    pub target: String,
    pub read_only: bool,
}

pub fn path(name: &str) -> PathBuf {
    Path::new(SETTINGS_DIR).join(format!("{name}.nspawn"))
}

#[cfg(test)]
pub fn render(s: &MachineSettings) -> String {
    render_with(s, &NamespaceRoute::Settings)
}

pub fn render_with(s: &MachineSettings, route: &NamespaceRoute) -> String {
    let mut out = format!(
        "# Generated by nspawn for image {}; do not edit.\n[Exec]\n",
        s.name
    );
    let mut private_users = true;
    if s.managed_userns {
        out.push_str("PrivateUsers=managed\n");
    } else if s.mode == Mode::App && s.network == Network::Bridge && s.bridge.is_some() {
        // A user namespace cannot join the network namespace prepared on the host
        // (EPERM: it belongs to the initial user namespace), so app machines on the
        // bridge run without one, as docker does.
        out.push_str("PrivateUsers=no\n");
        private_users = false;
    }
    match s.mode {
        Mode::Boot => out.push_str("Boot=yes\n"),
        Mode::App => {
            out.push_str("Boot=no\nProcessTwo=yes\n");
            if !s.command.is_empty() {
                let quoted: Vec<String> = s.command.iter().map(|a| quote(a)).collect();
                out.push_str(&format!("Parameters={}\n", quoted.join(" ")));
            }
            // A later assignment of the same variable wins, so -e comes after the image's.
            for var in s.run.env.iter().chain(s.extra_env) {
                out.push_str(&format!("Environment={}\n", quote(var)));
            }
            if let Some(dir) = &s.run.working_dir {
                out.push_str(&format!("WorkingDirectory={dir}\n"));
            }
            // nspawn's User= takes a name or a uid; the gid of docker's "uid:gid" form has
            // no counterpart and is left to the image's passwd.
            if let Some(user) = &s.run.user {
                let user = user.split_once(':').map(|(u, _)| u).unwrap_or(user);
                if !user.is_empty() {
                    out.push_str(&format!("User={user}\n"));
                }
            }
            // What a stop of the unit sends the stub init: a poweroff request. The image's
            // stop signal is what `nspawn stop` sends the program itself.
            out.push_str("KillSignal=SIGRTMIN+4\n");
        }
    }
    let mut files: Vec<String> = Vec::new();
    match s.network {
        Network::Host => out.push_str("\n[Network]\nVirtualEthernet=no\n"),
        Network::Bridge if s.no_network => out.push_str("\n[Network]\nPrivate=yes\n"),
        Network::Bridge => {
            if let Some(b) = &s.bridge {
                let dir = b.files.display();
                match s.mode {
                    Mode::Boot => {
                        out.push_str(&format!("\n[Network]\nBridge={}\n", b.bridge));
                        // The extra veths come up unattached; the publish hook puts
                        // their host ends on their bridges.
                        for (i, host_end) in b.extras.iter().enumerate() {
                            out.push_str(&format!(
                                "VirtualEthernetExtra={host_end}:host{}\n",
                                i + 1
                            ));
                        }
                        for i in 0..=b.extras.len() {
                            files.push(format!(
                                "BindReadOnly={dir}/host{i}.network:/run/systemd/network/1{i}-host{i}.network"
                            ));
                        }
                        files.push(format!("BindReadOnly={dir}/hosts:/etc/hosts"));
                    }
                    Mode::App => {
                        if *route == NamespaceRoute::Settings {
                            out.push_str(&format!(
                                "\n[Network]\nNamespacePath={}\n",
                                crate::bridge::netns_path(s.name)
                            ));
                        }
                        files.push(format!("BindReadOnly={dir}/hosts:/etc/hosts"));
                        files.push(format!("BindReadOnly={dir}/resolv.conf:/etc/resolv.conf"));
                    }
                }
            }
        }
        Network::Veth => {}
    }
    // Under managed user namespaces nspawn cannot idmap binds: those volumes are attached
    // from the host once the machine runs (volmount), and a booted machine's
    // local-fs.target waits for them (on every backend, for the same guarantee).
    let rendered_binds: &[Bind] = if s.managed_userns { &[] } else { s.binds };
    if s.mode == Mode::Boot && !s.binds.is_empty() {
        if let Some(units) = s.volume_units {
            let units = units.display();
            files.push(format!(
                "BindReadOnly={units}/nspawn-volumes.service:/run/systemd/system/nspawn-volumes.service"
            ));
            files.push(format!(
                "BindReadOnly={units}/nspawn-volumes.conf:/run/systemd/system/local-fs.target.d/nspawn-volumes.conf"
            ));
        }
    }
    for bind in rendered_binds {
        // With private users the host's uid 0 is nobody inside; idmap makes root inside
        // the owner of what it writes, as docker users expect.
        let options = if private_users { ":idmap" } else { "" };
        files.push(format!(
            "{}={}:{}{options}",
            if bind.read_only {
                "BindReadOnly"
            } else {
                "Bind"
            },
            bind.source.display(),
            bind.target
        ));
    }
    if !files.is_empty() {
        out.push_str("\n[Files]\n");
        for line in files {
            out.push_str(&line);
            out.push('\n');
        }
    }
    out
}

/// The units mounted into a booted machine so that its boot waits for its volumes:
/// (service, drop-in for local-fs.target).
pub fn volume_wait_units(targets: &[String]) -> (String, String) {
    let list = targets
        .iter()
        .map(|t| quote(t))
        .collect::<Vec<_>>()
        .join(" ");
    let service = format!(
        "# Generated by nspawn; do not edit.\n[Unit]\nDescription=Wait for the volumes nspawn attaches from the host\nDefaultDependencies=no\nBefore=local-fs.target\n\n[Service]\nType=oneshot\nRemainAfterExit=yes\nExecStart=/bin/sh -c 'for p in {list}; do i=0; until mountpoint -q \"$p\"; do i=$((i+1)); if [ $i -ge 2400 ]; then echo \"$p: volume not attached\" >&2; exit 1; fi; sleep 0.05; done; done'\n"
    );
    let dropin = "# Generated by nspawn; do not edit.\n[Unit]\nWants=nspawn-volumes.service\nAfter=nspawn-volumes.service\n".to_string();
    (service, dropin)
}

/// The drop-in that calls nspawn around the unit's life, whoever starts it, and carries
/// the restart policy and limits. Returns whether it changed (a reload is due).
pub fn write_hooks(
    name: &str,
    config: &crate::config::Config,
    route: &NamespaceRoute,
    app_argv: Option<&[String]>,
    restart: Restart,
    limits: &Limits,
    remove_on_exit: bool,
) -> Result<bool> {
    let text = render_hooks(
        &hook_command(config)?,
        name,
        route,
        app_argv,
        restart,
        limits,
        remove_on_exit,
    );
    let dir = crate::backend::dropin_dir(name);
    let path = dir.join("nspawn-hooks.conf");
    if fs::read_to_string(&path)
        .map(|current| current == text)
        .unwrap_or(false)
    {
        return Ok(false);
    }
    fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
    fs::write(&path, text).with_context(|| format!("writing {}", path.display()))?;
    Ok(true)
}

/// How the hooks call this binary: its canonical path and the configuration it was given.
fn hook_command(config: &crate::config::Config) -> Result<String> {
    Ok(hook_argv(config)?
        .iter()
        .map(|arg| quote(arg))
        .collect::<Vec<_>>()
        .join(" "))
}

/// `hook_command` as an argv.
pub fn hook_argv(config: &crate::config::Config) -> Result<Vec<String>> {
    let exe = std::env::current_exe().context("locating the nspawn binary")?;
    let exe = replaced_binary(&exe)
        .filter(|path| path.exists())
        .unwrap_or(exe);
    let exe = fs::canonicalize(&exe).unwrap_or(exe);
    let mut argv = vec![exe.to_string_lossy().into_owned()];
    if let Some(path) = &config.config_path {
        argv.push("--config".to_string());
        argv.push(path.to_string_lossy().into_owned());
    }
    Ok(argv)
}

/// The argv systemd has loaded for an app machine's ExecStart=, which the drop-in
/// rewrites (`exec_start_override`). None for a booted machine.
pub async fn app_argv(
    sd: &Systemd,
    name: &str,
    mode: Mode,
    route: &NamespaceRoute,
) -> Result<Option<Vec<String>>> {
    if mode != Mode::App {
        return Ok(None);
    }
    Ok(Some(match route {
        NamespaceRoute::CommandLine(argv) => argv.clone(),
        NamespaceRoute::Settings => {
            sd.exec_start(&format!("systemd-nspawn@{name}.service"))
                .await?
        }
    }))
}

pub fn render_hooks(
    command: &str,
    name: &str,
    route: &NamespaceRoute,
    app_argv: Option<&[String]>,
    restart: Restart,
    limits: &Limits,
    remove_on_exit: bool,
) -> String {
    let mut text = String::from("# Generated by nspawn; do not edit.\n");
    let restart_setting = restart.unit_setting();
    if restart_setting.is_some() {
        // Restarted as long as it keeps failing, with a growing delay, as docker does it.
        text.push_str("[Unit]\nStartLimitIntervalSec=0\n");
    }
    // No rate limit: logs and attached runs read the machine's output from the journal.
    text.push_str(&format!(
        "[Service]\nExecStartPre={command} network prepare %i\nExecStartPost={command} network publish %i\nExecStopPost=-{command} network release %i\nLogRateLimitIntervalSec=0\n"
    ));
    if let Some(setting) = restart_setting {
        text.push_str(&format!(
            "Restart={setting}\nRestartSec=1s\nRestartSteps=5\nRestartMaxDelaySec=30s\n"
        ));
    }
    if remove_on_exit {
        // run --rm: the template restarts on a reboot (133); this machine ends instead.
        text.push_str("RestartForceExitStatus=\n");
    }
    if limits.memory > 0 {
        // As much swap again, docker's default; without it swap would be unbounded.
        text.push_str(&format!(
            "MemoryMax={0}\nMemorySwapMax={0}\n",
            limits.memory
        ));
    }
    if let Some(quota) = limits.cpu_quota() {
        text.push_str(&format!("CPUQuota={quota}\n"));
    }
    if limits.pids > 0 {
        text.push_str(&format!("TasksMax={}\n", limits.pids));
    }
    match (route, app_argv) {
        (NamespaceRoute::CommandLine(argv), _) => {
            text.push_str(&exec_start_override(command, argv, name, true));
        }
        (NamespaceRoute::Settings, Some(argv)) => {
            text.push_str(&exec_start_override(command, argv, name, false));
        }
        (NamespaceRoute::Settings, None) => {}
    }
    text
}

/// An app machine's ExecStart=: the loaded argv behind `nspawn attach-exec` (src/attach.rs),
/// without the override of ours it may carry and without --console, which only a run
/// chooses.
/// With `namespace` it carries --network-namespace-path= instead of the options that
/// conflict with it (in their `--option=value` form). Applied to its own output it gives
/// the same lines.
pub fn exec_start_override(command: &str, argv: &[String], name: &str, namespace: bool) -> String {
    const CONFLICTING: &[&str] = &[
        "--network-veth",
        "-n",
        "--network-namespace-path",
        "--network-bridge",
        "--network-zone",
        "--network-interface",
        "--network-macvlan",
        "--network-ipvlan",
        "--network-veth-extra",
    ];
    let is = |arg: &str, option: &str| arg == option || arg.starts_with(&format!("{option}="));
    let argv = unwrapped(argv);
    let mut kept: Vec<String> = argv
        .iter()
        .filter(|arg| !is(arg, "--console") && !is(arg, "--network-namespace-path"))
        .filter(|arg| !namespace || !CONFLICTING.iter().any(|option| is(arg, option)))
        .map(|arg| unit_quote(arg))
        .collect();
    if namespace {
        kept.push(format!(
            "--network-namespace-path={}",
            unit_quote(&crate::bridge::netns_path(name))
        ));
    }
    format!(
        "ExecStart=\nExecStart={command} attach-exec {} -- {}\n",
        unit_quote(name),
        kept.join(" ")
    )
}

fn unwrapped(argv: &[String]) -> &[String] {
    match argv.iter().position(|a| a == "--") {
        Some(end) if argv[..end].iter().any(|a| a == "attach-exec") => &argv[end + 1..],
        _ => argv,
    }
}

/// One ExecStart= argument: `%` doubled, anything unusual double-quoted with escapes.
pub fn unit_quote(arg: &str) -> String {
    let plain = !arg.is_empty()
        && arg
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || "-_.:/=@+,".contains(c));
    if plain {
        return arg.to_string();
    }
    let mut quoted = String::from("\"");
    for c in arg.chars() {
        match c {
            '"' => quoted.push_str("\\\""),
            '\\' => quoted.push_str("\\\\"),
            '%' => quoted.push_str("%%"),
            _ => quoted.push(c),
        }
    }
    quoted.push('"');
    quoted
}

/// Writes the file when it changed, root's alone: -e often carries secrets.
pub fn write(s: &MachineSettings, route: &NamespaceRoute) -> Result<()> {
    write_private(&path(s.name), &render_with(s, route))
}

fn write_private(path: &Path, wanted: &str) -> Result<()> {
    use std::io::Write;
    use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
    if fs::read_to_string(path)
        .map(|current| current == wanted)
        .unwrap_or(false)
    {
        // Same content: only the mode may be wrong.
        return fs::set_permissions(path, fs::Permissions::from_mode(0o600))
            .with_context(|| format!("restricting {} to root", path.display()));
    }
    let dir = path.parent().unwrap_or(Path::new("."));
    fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    // Through a new file and a rename: never half written, never readable by others.
    let name = path.file_name().unwrap_or_default().to_string_lossy();
    let tmp = dir.join(format!(".{name}.{}", crate::store::unique_suffix()));
    let written = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(&tmp)
        .and_then(|mut file| file.write_all(wanted.as_bytes()))
        .and_then(|()| fs::rename(&tmp, path));
    if written.is_err() {
        let _ = fs::remove_file(&tmp);
    }
    written.with_context(|| format!("writing {}", path.display()))
}

pub fn remove(name: &str) {
    let _ = fs::remove_file(path(name));
}

/// Quotes an argument for config_parse_strv, where backslashes escape nothing and
/// adjacent quoted pieces join: single quotes around it, and each single quote inside in
/// double quotes between two such pieces.
pub fn quote(arg: &str) -> String {
    if !arg.is_empty()
        && !arg
            .chars()
            .any(|c| c.is_whitespace() || matches!(c, '"' | '\'' | '\\'))
    {
        return arg.to_string();
    }
    let mut out = String::new();
    for (i, piece) in arg.split('\'').enumerate() {
        if i > 0 {
            out.push_str("\"'\"");
        }
        if !piece.is_empty() {
            out.push('\'');
            out.push_str(piece);
            out.push('\'');
        }
    }
    if out.is_empty() {
        "''".to_string()
    } else {
        out
    }
}

/// After a package upgrade replaced the binary, /proc/self/exe reads "<path> (deleted)";
/// the hooks must name the path itself.
fn replaced_binary(exe: &Path) -> Option<PathBuf> {
    exe.to_str()?.strip_suffix(" (deleted)").map(PathBuf::from)
}

#[cfg(test)]
mod tests {
    #[test]
    fn a_replaced_binary_still_names_its_path() {
        assert_eq!(
            replaced_binary(Path::new("/usr/bin/nspawn (deleted)")),
            Some(PathBuf::from("/usr/bin/nspawn"))
        );
        assert_eq!(replaced_binary(Path::new("/usr/bin/nspawn")), None);
        assert_eq!(replaced_binary(Path::new("/usr/local/bin/nspawn")), None);
    }

    use super::*;

    #[test]
    fn settings_are_root_s_alone() {
        use std::os::unix::fs::PermissionsExt;
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("nspawn/web.nspawn");
        let mode = |p: &Path| fs::metadata(p).unwrap().permissions().mode() & 0o777;
        write_private(&path, "Environment=PASSWORD=secret\n").unwrap();
        assert_eq!(mode(&path), 0o600);
        assert_eq!(
            fs::read_to_string(&path).unwrap(),
            "Environment=PASSWORD=secret\n"
        );
        fs::set_permissions(&path, fs::Permissions::from_mode(0o644)).unwrap();
        write_private(&path, "Environment=PASSWORD=secret\n").unwrap();
        assert_eq!(
            mode(&path),
            0o600,
            "one an earlier version left open is closed"
        );
        write_private(&path, "Environment=PASSWORD=other\n").unwrap();
        assert_eq!(mode(&path), 0o600);
        assert_eq!(
            fs::read_dir(path.parent().unwrap()).unwrap().count(),
            1,
            "no temporary file left"
        );
    }

    #[test]
    fn quoting() {
        assert_eq!(quote("nginx"), "nginx");
        assert_eq!(quote("daemon off;"), "'daemon off;'");
        assert_eq!(quote("a\"b"), "'a\"b'");
        assert_eq!(quote("it's"), "'it'\"'\"'s'");
        assert_eq!(quote("'"), "\"'\"");
        assert_eq!(quote("back\\slash"), "'back\\slash'");
        assert_eq!(quote(""), "''");
        assert_eq!(quote("PATH=/usr/bin"), "PATH=/usr/bin");
        assert_eq!(quote("/bin/sh"), "/bin/sh");
    }

    #[test]
    fn app_machines_start_behind_attach_exec() {
        let command = "/usr/bin/nspawn";
        let argv: Vec<String> = [
            "systemd-nspawn",
            "--quiet",
            "--keep-unit",
            "--boot",
            "--link-journal=try-guest",
            "--network-veth",
            "-U",
            "--settings=override",
            "--machine=web",
        ]
        .iter()
        .map(|s| s.to_string())
        .collect();
        let text = exec_start_override(command, &argv, "web", true);
        assert_eq!(
            text,
            "ExecStart=\nExecStart=/usr/bin/nspawn attach-exec web -- systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest -U --settings=override --machine=web --network-namespace-path=/run/netns/nspawn-web\n"
        );
        // What systemd loads from that drop-in gives the same drop-in again.
        let loaded: Vec<String> = text.lines().nth(1).unwrap()["ExecStart=".len()..]
            .split(' ')
            .map(|s| s.to_string())
            .collect();
        assert_eq!(exec_start_override(command, &loaded, "web", true), text);
        // Without the namespace on the command line (systemd 259 and newer, or a network
        // other than the bridge), the path a loaded drop-in added goes, and so does a
        // --console of whatever origin: only a run chooses that.
        let mut console = loaded.clone();
        console.push("--console=interactive".into());
        assert_eq!(
            exec_start_override(command, &console, "web", false),
            "ExecStart=\nExecStart=/usr/bin/nspawn attach-exec web -- systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest -U --settings=override --machine=web\n"
        );
        assert_eq!(
            exec_start_override(command, &argv, "web", false),
            "ExecStart=\nExecStart=/usr/bin/nspawn attach-exec web -- systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth -U --settings=override --machine=web\n"
        );
        // Every option that cannot go with a namespace path is dropped, whatever its value.
        let bridged: Vec<String> = [
            "systemd-nspawn",
            "--network-bridge=br0",
            "-n",
            "--network-zone=z",
            "--network-interface=eth1",
            "--machine=%i",
        ]
        .iter()
        .map(|s| s.to_string())
        .collect();
        assert_eq!(
            exec_start_override(command, &bridged, "a", true),
            "ExecStart=\nExecStart=/usr/bin/nspawn attach-exec a -- systemd-nspawn \"--machine=%%i\" --network-namespace-path=/run/netns/nspawn-a\n"
        );
        assert_eq!(unit_quote("plain-arg=1"), "plain-arg=1");
        assert_eq!(unit_quote("with space"), "\"with space\"");
        assert_eq!(unit_quote("q\"b\\"), "\"q\\\"b\\\\\"");
        assert_eq!(unit_quote(""), "\"\"");
    }

    #[test]
    fn renders_several_networks_and_none() {
        let run = RunSpec::default();
        let extras = vec!["vb1-fedora-44".to_string(), "vb2-fedora-44".to_string()];
        let booted = render(&MachineSettings {
            name: "fedora-44",
            managed_userns: false,
            mode: Mode::Boot,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Bridge,
            no_network: false,
            bridge: Some(BridgeMount {
                bridge: "nsbr-front",
                files: Path::new("/var/lib/nspawn/machines/fedora-44"),
                extras: &extras,
            }),
        });
        assert!(booted.contains("[Network]\nBridge=nsbr-front\nVirtualEthernetExtra=vb1-fedora-44:host1\nVirtualEthernetExtra=vb2-fedora-44:host2\n"));
        assert!(booted.contains("host1.network:/run/systemd/network/11-host1.network\n"));
        assert!(booted.contains("host2.network:/run/systemd/network/12-host2.network\n"));
        let none = render(&MachineSettings {
            name: "web",
            managed_userns: false,
            mode: Mode::App,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Bridge,
            no_network: true,
            bridge: None,
        });
        assert!(none.contains("[Network]\nPrivate=yes\n"));
        assert!(
            !none.contains("PrivateUsers=no"),
            "a user namespace goes with no network"
        );
    }

    #[test]
    fn renders_boot_and_app_machines() {
        let run = RunSpec::default();
        let boot = render(&MachineSettings {
            name: "fedora-44",
            managed_userns: true,
            mode: Mode::Boot,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Veth,
            no_network: false,
            bridge: None,
        });
        assert_eq!(boot, "# Generated by nspawn for image fedora-44; do not edit.\n[Exec]\nPrivateUsers=managed\nBoot=yes\n");

        let bridged = render(&MachineSettings {
            name: "fedora-44",
            managed_userns: false,
            mode: Mode::Boot,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Bridge,
            no_network: false,
            bridge: Some(BridgeMount {
                bridge: "nspawn0",
                files: Path::new("/var/lib/nspawn/machines/fedora-44"),
                extras: &[],
            }),
        });
        assert!(bridged.contains("Boot=yes\n\n[Network]\nBridge=nspawn0\n\n[Files]\n"));
        assert!(bridged.contains("BindReadOnly=/var/lib/nspawn/machines/fedora-44/host0.network:/run/systemd/network/10-host0.network\n"));
        assert!(
            bridged.ends_with("BindReadOnly=/var/lib/nspawn/machines/fedora-44/hosts:/etc/hosts\n")
        );

        let app_bridged = render(&MachineSettings {
            name: "web",
            managed_userns: false,
            mode: Mode::App,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Bridge,
            no_network: false,
            bridge: Some(BridgeMount {
                bridge: "nspawn0",
                files: Path::new("/var/lib/nspawn/machines/web"),
                extras: &[],
            }),
        });
        assert!(app_bridged.contains("[Exec]\nPrivateUsers=no\nBoot=no\n"));
        assert!(app_bridged.contains("[Network]\nNamespacePath=/run/netns/nspawn-web\n"));
        assert!(!app_bridged.contains("Bridge="));
        // Before systemd 259 the namespace goes on the command line and the file has no
        // [Network] section, so the template's network options stay in force there.
        let on_command_line = render_with(
            &MachineSettings {
                name: "web",
                managed_userns: false,
                mode: Mode::App,
                run: &run,
                command: &run.argv(),
                extra_env: &[],
                binds: &[],
                volume_units: None,
                network: Network::Bridge,
                no_network: false,
                bridge: Some(BridgeMount {
                    bridge: "nspawn0",
                    files: Path::new("/var/lib/nspawn/machines/web"),
                    extras: &[],
                }),
            },
            &NamespaceRoute::CommandLine(vec!["systemd-nspawn".to_string()]),
        );
        assert!(!on_command_line.contains("[Network]"));
        assert!(on_command_line.contains("resolv.conf:/etc/resolv.conf\n"));
        assert!(app_bridged.ends_with("BindReadOnly=/var/lib/nspawn/machines/web/hosts:/etc/hosts\nBindReadOnly=/var/lib/nspawn/machines/web/resolv.conf:/etc/resolv.conf\n"));
        let app_volume = render(&MachineSettings {
            name: "web",
            managed_userns: false,
            mode: Mode::App,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[Bind {
                source: PathBuf::from("/srv/www"),
                target: "/www".into(),
                read_only: false,
            }],
            volume_units: None,
            network: Network::Bridge,
            no_network: false,
            bridge: Some(BridgeMount {
                bridge: "nspawn0",
                files: Path::new("/var/lib/nspawn/machines/web"),
                extras: &[],
            }),
        });
        let mstack_volume = render(&MachineSettings {
            name: "db",
            managed_userns: true,
            mode: Mode::Boot,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[Bind {
                source: PathBuf::from("/srv/pg"),
                target: "/var/lib/pgsql".into(),
                read_only: false,
            }],
            volume_units: Some(Path::new("/var/lib/nspawn/machines/db/units")),
            network: Network::Host,
            no_network: false,
            bridge: None,
        });
        // Managed user namespaces: no Bind= (attached from the host), but the wait units.
        assert!(!mstack_volume.contains("Bind=/srv/pg"));
        let overlay_volume = render(&MachineSettings {
            name: "db",
            managed_userns: false,
            mode: Mode::Boot,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[Bind {
                source: PathBuf::from("/srv/pg"),
                target: "/var/lib/pgsql".into(),
                read_only: false,
            }],
            volume_units: Some(Path::new("/var/lib/nspawn/machines/db/units")),
            network: Network::Host,
            no_network: false,
            bridge: None,
        });
        // Other backends: the bind itself plus the same wait units.
        assert!(overlay_volume.contains("Bind=/srv/pg:/var/lib/pgsql:idmap\n"));
        assert!(overlay_volume
            .contains("nspawn-volumes.service:/run/systemd/system/nspawn-volumes.service\n"));
        assert!(mstack_volume.contains("BindReadOnly=/var/lib/nspawn/machines/db/units/nspawn-volumes.service:/run/systemd/system/nspawn-volumes.service\n"));
        assert!(mstack_volume.contains("local-fs.target.d/nspawn-volumes.conf\n"));
        let (service, dropin) =
            volume_wait_units(&["/var/lib/pgsql".to_string(), "/etc/app".to_string()]);
        assert!(service.contains("Before=local-fs.target"));
        assert!(service.contains("for p in /var/lib/pgsql /etc/app;"));
        assert!(dropin.contains("Wants=nspawn-volumes.service\nAfter=nspawn-volumes.service"));
        // No user namespace on the bridge, so no idmap either.
        assert!(app_volume.ends_with("BindReadOnly=/var/lib/nspawn/machines/web/resolv.conf:/etc/resolv.conf\nBind=/srv/www:/www\n"));

        let run = RunSpec {
            healthcheck: None,
            entrypoint: Vec::new(),
            cmd: vec!["nginx".into(), "-g".into(), "daemon off;".into()],
            command: Vec::new(),
            env: vec!["PATH=/usr/bin".into(), "GREETING=hello world".into()],
            working_dir: Some("/srv".into()),
            user: Some("nginx".into()),
            stop_signal: Some("SIGQUIT".into()),
            labels: Default::default(),
        };
        let app = render(&MachineSettings {
            name: "web",
            managed_userns: false,
            mode: Mode::App,
            run: &run,
            command: &run.argv(),
            extra_env: &[],
            binds: &[],
            volume_units: None,
            network: Network::Host,
            no_network: false,
            bridge: None,
        });
        assert!(app.contains("Boot=no\nProcessTwo=yes\n"));
        assert!(app.contains("Parameters=nginx -g 'daemon off;'\n"));
        assert!(app.contains("Environment=PATH=/usr/bin\nEnvironment='GREETING=hello world'\n"));
        assert!(app.contains("WorkingDirectory=/srv\nUser=nginx\nKillSignal=SIGRTMIN+4\n"));
        assert!(app.ends_with("[Network]\nVirtualEthernet=no\n"));

        let numeric_user = RunSpec {
            user: Some("1000:1000".into()),
            ..RunSpec::default()
        };
        let binds = vec![
            Bind {
                source: PathBuf::from("/srv/data"),
                target: "/data".into(),
                read_only: false,
            },
            Bind {
                source: PathBuf::from("/var/lib/nspawn/volumes/cfg"),
                target: "/etc/app".into(),
                read_only: true,
            },
        ];
        let text = render(&MachineSettings {
            name: "x",
            managed_userns: false,
            mode: Mode::App,
            run: &numeric_user,
            command: &["/bin/sleep".to_string(), "infinity".to_string()],
            extra_env: &["GREETING=hi".to_string()],
            binds: &binds,
            volume_units: None,
            network: Network::Veth,
            no_network: false,
            bridge: None,
        });
        assert!(
            text.contains("User=1000\n"),
            "a numeric user applies, the gid is nspawn's business"
        );
        assert!(text.contains(
            "Parameters=/bin/sleep infinity\nEnvironment=GREETING=hi\nUser=1000\nKillSignal=SIGRTMIN+4\n"
        ));
        assert!(!text.contains("[Network]"));
        // The template's -U applies here, so volumes are idmapped.
        assert!(text.ends_with("[Files]\nBind=/srv/data:/data:idmap\nBindReadOnly=/var/lib/nspawn/volumes/cfg:/etc/app:idmap\n"));
    }

    #[test]
    fn the_hooks_drop_in_carries_the_policy_and_the_limits() {
        let command = "/usr/bin/nspawn";
        let plain = render_hooks(
            command,
            "web",
            &NamespaceRoute::Settings,
            None,
            Restart::No,
            &Limits::default(),
            false,
        );
        assert_eq!(
            plain,
            "# Generated by nspawn; do not edit.\n[Service]\nExecStartPre=/usr/bin/nspawn network prepare %i\nExecStartPost=/usr/bin/nspawn network publish %i\nExecStopPost=-/usr/bin/nspawn network release %i\nLogRateLimitIntervalSec=0\n",
            "a booted machine without a policy or limits: the hooks alone"
        );
        let on_failure = render_hooks(
            command,
            "web",
            &NamespaceRoute::Settings,
            None,
            Restart::OnFailure,
            &Limits::default(),
            false,
        );
        assert!(on_failure.starts_with(
            "# Generated by nspawn; do not edit.\n[Unit]\nStartLimitIntervalSec=0\n[Service]\n"
        ));
        assert!(on_failure.ends_with(
            "Restart=on-failure\nRestartSec=1s\nRestartSteps=5\nRestartMaxDelaySec=30s\n"
        ));
        for policy in [Restart::Always, Restart::UnlessStopped] {
            let text = render_hooks(
                command,
                "web",
                &NamespaceRoute::Settings,
                None,
                policy,
                &Limits::default(),
                false,
            );
            assert!(text.contains("\nRestart=always\n"));
        }
        let limited = render_hooks(
            command,
            "web",
            &NamespaceRoute::Settings,
            None,
            Restart::No,
            &Limits {
                memory: 64 << 20,
                milli_cpus: 500,
                pids: 100,
            },
            false,
        );
        assert!(!limited.contains("[Unit]"));
        assert!(limited
            .ends_with("MemoryMax=67108864\nMemorySwapMax=67108864\nCPUQuota=50%\nTasksMax=100\n"));
        let only_cpus = render_hooks(
            command,
            "web",
            &NamespaceRoute::Settings,
            None,
            Restart::No,
            &Limits {
                memory: 0,
                milli_cpus: 333,
                pids: 0,
            },
            false,
        );
        assert!(
            only_cpus.ends_with("network release %i\nLogRateLimitIntervalSec=0\nCPUQuota=33.3%\n")
        );
        let argv: Vec<String> = [
            "systemd-nspawn",
            "--quiet",
            "--network-veth",
            "--machine=web",
        ]
        .iter()
        .map(|s| s.to_string())
        .collect();
        let old_systemd = render_hooks(
            command,
            "web",
            &NamespaceRoute::CommandLine(argv.clone()),
            Some(&argv),
            Restart::Always,
            &Limits::default(),
            false,
        );
        assert!(old_systemd.ends_with(&exec_start_override(command, &argv, "web", true)));
        assert!(old_systemd.contains("RestartMaxDelaySec=30s\nExecStart="));
        let app = render_hooks(
            command,
            "web",
            &NamespaceRoute::Settings,
            Some(&argv),
            Restart::No,
            &Limits::default(),
            false,
        );
        assert!(app.ends_with(&exec_start_override(command, &argv, "web", false)));
    }
}
